format_version: 1
pipelines:
  PipelineName0001:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-6286498:
        git: https://github.com/eddemo0007/GoCD-WebGoat.Net-Public
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - StageDetails0001:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          JobAndTasks0001:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Type your tasks below at the prompt
                command: echo
                run_if: passed
